
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - db:/db.sqlite3
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
    ports:
      - "2000:8000"
    networks:
      - app-network


volumes:
  static_volume:
  media_volume:
  db:

networks:
  app-network:
    driver: bridge
