# Generated by Django 5.2.7 on 2025-10-08 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_set', to='auth.group'),
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='laboratory.course')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_groups',
            field=models.ManyToManyField(blank=True, related_name='students', to='laboratory.studentgroup'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
