# Generated by Django 5.2.7 on 2025-10-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_alter_customuser_groups_studentgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='student_groups',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='laboratory.studentgroup'),
        ),
    ]
