# Generated by Django 5.2.7 on 2026-03-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_admin_extensions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assignmentevent',
            new_name='laboratory__student_e4f188_idx',
            old_name='laboratory__student_8a6a7e_idx',
        ),
    ]
