# Generated by Django 5.2.7 on 2026-03-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_site_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Фон курса', 'verbose_name_plural': 'Фоны курса'},
        ),
        migrations.AddField(
            model_name='assignmentevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='behavior_clipboard_changes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='behavior_gpt_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='behavior_keystrokes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='behavior_paste_chars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='behavior_paste_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='behavior_tab_switches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignmentevent',
            name='event_type',
            field=models.CharField(choices=[('OPEN_PAGE', 'Открыл страницу'), ('START_WORK', 'Начал работу'), ('CLIPBOARD_CHANGE', 'Изменение буфера обмена'), ('PASTE_DETECTED', 'Вставка из буфера'), ('TAB_SWITCH', 'Переключение вкладки')], max_length=20),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='image',
            field=models.ImageField(upload_to='course_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='courseimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись'),
        ),
    ]
