# Generated by Django 5.2.7 on 2026-03-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_behavior_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentevent',
            name='event_type',
            field=models.CharField(choices=[('OPEN_PAGE', 'Открыл страницу'), ('START_WORK', 'Начал работу'), ('CLIPBOARD_CHANGE', 'Изменение буфера обмена'), ('PASTE_DETECTED', 'Вставка из буфера'), ('TAB_SWITCH', 'Переключение вкладки'), ('KEYLOG_BATCH', 'Батч нажатий клавиш')], max_length=20),
        ),
    ]
