# Generated by Django 5.2.7 on 2026-06-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0015_deadline_override'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deadlineoverride',
            name='deadline_override_user_xor_group',
        ),
        migrations.AddConstraint(
            model_name='deadlineoverride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student_group__isnull', True), ('user__isnull', False)), models.Q(('student_group__isnull', False), ('user__isnull', True)), _connector='OR'), name='deadline_override_user_xor_group'),
        ),
    ]
